version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: nest_restaurant_backend
    volumes:
     - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: develop*123
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"